on:
  push:
    branches:
      - master

jobs:
  tsc:
    name: Compile typescript
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Installing Node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Installing project dependencies
      run: npm install
    - name: Installing Typescript globally
      run: npm install -g typescript
    - name: Compiling sources
      run: tsc
    - name: Remove sources
      run: rm -r src
    - name: Move content
      run: mv ${{ github.workspace }}/dist/* ${{ github.workspace }}
    - name: Remove dist
      run: rm -r dist
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ${{ github.workspace }}
  Listing-Files:
    name: Building Docker image
    needs: [tsc]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
      - id: tagName
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace }}
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/${{ steps.tagName.outputs.lowercase }}:latest